[package]
name = "protobuf"
version = "0.1.0"
authors = ["xkevin190 <kevinvelasco193@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.6"
bytes = "0.4"


[build-dependencies]
prost-build = "0.5"